version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  api:
    build: .
    depends_on: 
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://localhost:7575
    ports:
      - 7575:7575